# Generated by Django 2.2 on 2020-12-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='manager_id',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
